version: '3'
services: 
    
    jenkins2:
        container_name: jenkins-master
        build: 
            context: ./master
            dockerfile: Dockerfile
        ports: 
            - 8080:8080
            - 50000:50000
        volumes: 
            - ./jenkins_home:/var/jenkins_home
        restart: always

networks: 
    default:
        external: 
            name: cicd