
def instanceFileConfig = 'instances.json'

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                deployInEachInstance()
            }
        }
    }
}

def deployInEachInstance() {

    sh "ls"

    // Get instance's info object from file
    def instances = readJSON file: instanceFileConfig
    instances.each {
        echo "${it.ip}"

        // do deploy here
    }
}